"""Compile the normalized run table into the dashboard's data bundle.

The bundle is deliberately *run-level*, not pre-aggregated: the dashboard's
filter row (level / station / suite / time range) has to re-slice the data, and
every stat, chart, and table must agree on the same slice. Aggregating in the
browser is the only way that stays true.

Output is JavaScript (``window.__FACTORY_METRICS__ = {...}``) rather than JSON so
the dashboard also opens straight off disk over ``file://``.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import config
from .hourly import summary

#: Keys are short because this ships to the browser once per page load.
FAILURE_LIMIT_PER_RUN = 25


def build_bundle(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Turn ``runs.json`` into the compact structure ``app.js`` expects."""
    runs: List[Dict[str, Any]] = payload.get("runs", [])

    compact = []
    for run in runs:
        if not run.get("startTs"):
            continue  # cannot be placed on an hourly timeline
        counts = run.get("testCounts") or {}
        failures = (run.get("failures") or [])[:FAILURE_LIMIT_PER_RUN]
        compact.append(
            {
                "id": run.get("runId"),
                "lv": run.get("level"),
                "dut": run.get("dutSerial"),
                "st": run.get("station") or "(unknown)",
                "su": run.get("suite") or "(unknown)",
                "ver": run.get("version") or "(unknown)",
                "t": int(run["startTs"]),
                "d": _round(run.get("durationSec")),
                "s": run.get("status", "unknown"),
                "a": run.get("attempt", 1),
                "nt": sum(counts.get(key, 0) for key in ("pass", "fail", "error")),
                "nf": counts.get("fail", 0) + counts.get("error", 0),
                "f": [
                    {"t": f.get("test"), "c": f.get("code"), "l": f.get("log")}
                    for f in failures
                ],
            }
        )

    dropped = len(runs) - len(compact)
    return {
        "schemaVersion": 1,
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "collectedAt": payload.get("generatedAt"),
        "timezone": payload.get("timezone", config.timezone_name()),
        "window": payload.get("window", {}),
        "levels": sorted({run["lv"] for run in compact if run.get("lv")}),
        "stations": sorted({run["st"] for run in compact}),
        "suites": sorted({run["su"] for run in compact}),
        "source": payload.get("source", "eos-api"),
        "notes": {
            "runsDroppedNoTimestamp": dropped,
            "problems": payload.get("problems", [])[:20],
        },
        "overall": _jsonable(summary(payload.get("runs", []), payload.get("timezone"))),
        "runs": compact,
    }


def _round(value: Any) -> Optional[float]:
    if value in (None, ""):
        return None
    return round(float(value), 1)


def _jsonable(value: Any) -> Any:
    return json.loads(json.dumps(value, default=float))


def write_bundle(bundle: Dict[str, Any], path: Optional[Path] = None) -> Path:
    target = path or config.DASHBOARD_BUNDLE
    target.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(bundle, separators=(",", ":"))
    target.write_text(
        "// Generated by `python -m factory.cli build` — do not edit.\n"
        "window.__FACTORY_METRICS__ = {};\n".format(body),
        encoding="utf-8",
    )
    return target
