#!/bin/bash
# Publish dashboard/ to the gh-pages branch, which GitHub Pages serves.
#
# WHY AN ORPHAN FORCE-PUSH
# The data bundles are ~650 KB and are rebuilt every hour. Committing them onto
# a branch with history would add that much to the repository every hour
# forever. Each publish is therefore a single orphan commit that replaces the
# branch: the served content is always current, old blobs become unreachable,
# and the repository stays roughly one copy in size. There is no history to
# lose here — the dashboard is a live view, and `main` keeps all the code.
#
# WHAT GETS PUBLISHED
# Only dashboard/ — the HTML, CSS, JS and the generated data bundles. The raw
# run table, the HTTP cache, the fetch state and the CA bundle stay local.
#
# The Pages site is PRIVATE (public: false): an obfuscated *.pages.github.io
# URL that requires an authenticated Etched org member. It still carries real
# factory data — DUT serials, failure signatures, yield — so keep it that way.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO" || exit 1

BRANCH="${PAGES_BRANCH:-gh-pages}"
REMOTE="${PAGES_REMOTE:-origin}"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

if [ ! -f "$REPO/dashboard/data/stations.js" ]; then
    echo "No data bundle — run 'make refresh' first." >&2
    exit 1
fi

cp -R "$REPO/dashboard/." "$STAGE/"
touch "$STAGE/.nojekyll"          # serve files verbatim, no Jekyll processing

# A published page should say where it came from and that it is not public.
cat > "$STAGE/README.md" <<'EOF'
Generated by factory_data_analysis — do not edit or commit here.
This branch is replaced wholesale on every publish.
EOF

cd "$STAGE" || exit 1
git init -q -b "$BRANCH"
git config user.email "${GIT_AUTHOR_EMAIL:-noreply@etched.com}"
git config user.name  "${GIT_AUTHOR_NAME:-factory-data-analysis}"
git config credential."https://github.com".helper '!gh auth git-credential'
git add -A
git commit -q -m "Publish dashboard $(date -u +%Y-%m-%dT%H:%M:%SZ)"

url="$(cd "$REPO" && git remote get-url "$REMOTE")"
if ! git push -q -f "$url" "$BRANCH" 2>&1 | tail -3; then
    echo "publish: push failed" >&2
    exit 1
fi

echo "Published $(du -sh "$STAGE" | cut -f1) to $BRANCH"
