#!/bin/bash
# Publish dashboard/ to wherever this machine serves it from.
#
# TWO TARGETS, ONE SCRIPT
# Set FACTORY_WEB_ROOT and publishing is a copy into a directory an nginx
# already serves (the always-on host inside the network). Leave it unset and
# publishing is an orphan force-push to gh-pages (a laptop, which has no web
# server of its own). Everything upstream — `make update`, the hourly job, the
# Update button — calls this one script either way, so the repo keeps its one
# update path and the two hosts cannot drift into two different publish
# behaviours.
#
# WHY AN ORPHAN FORCE-PUSH (gh-pages target)
# The data bundles are ~650 KB and are rebuilt every hour. Committing them onto
# a branch with history would add that much to the repository every hour
# forever. Each publish is therefore a single orphan commit that replaces the
# branch: the served content is always current, old blobs become unreachable,
# and the repository stays roughly one copy in size. There is no history to
# lose here — the dashboard is a live view, and `main` keeps all the code.
#
# WHAT GETS PUBLISHED
# Only dashboard/ — the HTML, CSS, JS and the generated data bundles. The raw
# run table, the HTTP cache, the fetch state and the CA bundle stay local.
#
# The Pages site is PRIVATE (public: false): an obfuscated *.pages.github.io
# URL that requires an authenticated Etched org member. It still carries real
# factory data — DUT serials, failure signatures, yield — so keep it that way.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO" || exit 1

# `make publish` reaches this script directly, without going through
# hourly_refresh.sh, so read .env here too — otherwise the publish target would
# depend on which entry point was used.
[ -f "$REPO/.env" ] && set -a && . "$REPO/.env" && set +a

BRANCH="${PAGES_BRANCH:-gh-pages}"
REMOTE="${PAGES_REMOTE:-origin}"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

if [ ! -f "$REPO/dashboard/data/stations.js" ]; then
    echo "No data bundle — run 'make refresh' first." >&2
    exit 1
fi

# ------------------------------------------------------- target 1: a web root
# A host that serves the dashboard itself has nothing to push: publishing is a
# copy into the directory nginx already points at. No git, no credential, no
# remote — which is the point, since that host holds the API key and runs
# unattended.
if [ -n "${FACTORY_WEB_ROOT:-}" ]; then
    if [ ! -d "$FACTORY_WEB_ROOT" ]; then
        echo "publish: FACTORY_WEB_ROOT=$FACTORY_WEB_ROOT is not a directory" >&2
        exit 1
    fi

    # --delete so a page removed from dashboard/ stops being served rather than
    # lingering as an orphan. Copy in place rather than moving a staged
    # directory: files created inside the web root inherit its SELinux context,
    # while a directory moved in from $HOME would keep the home context and
    # nginx would serve 403s.
    if ! rsync -a --delete --exclude '.git' "$REPO/dashboard/" "$FACTORY_WEB_ROOT/"; then
        echo "publish: copy to $FACTORY_WEB_ROOT failed" >&2
        exit 1
    fi

    echo "Published $(du -sh "$FACTORY_WEB_ROOT" | cut -f1) to $FACTORY_WEB_ROOT"
    exit 0
fi

# ------------------------------------------------------ target 2: gh-pages
cp -R "$REPO/dashboard/." "$STAGE/"
touch "$STAGE/.nojekyll"          # serve files verbatim, no Jekyll processing

# A published page should say where it came from and that it is not public.
cat > "$STAGE/README.md" <<'EOF'
Generated by factory_data_analysis — do not edit or commit here.
This branch is replaced wholesale on every publish.
EOF

cd "$STAGE" || exit 1
git init -q -b "$BRANCH"
git config user.email "${GIT_AUTHOR_EMAIL:-noreply@etched.com}"
git config user.name  "${GIT_AUTHOR_NAME:-factory-data-analysis}"
git config credential."https://github.com".helper '!gh auth git-credential'
git add -A
git commit -q -m "Publish dashboard $(date -u +%Y-%m-%dT%H:%M:%SZ)"

url="$(cd "$REPO" && git remote get-url "$REMOTE")"
if ! git push -q -f "$url" "$BRANCH" 2>&1 | tail -3; then
    echo "publish: push failed" >&2
    # Reaching the gh-pages path at all is the more likely mistake on a host
    # that is supposed to publish to a directory: FACTORY_WEB_ROOT lives in
    # .env, and .env is exactly the file a careless deploy overwrites.
    echo "publish: FACTORY_WEB_ROOT is not set, so this tried to push to" \
         "$BRANCH. On a host that serves the dashboard itself, set" \
         "FACTORY_WEB_ROOT in .env and publishing becomes a local copy." >&2
    exit 1
fi

echo "Published $(du -sh "$STAGE" | cut -f1) to $BRANCH"
